export * as userService from './user.service'
export * as hostService from './hospital.service'
export * as serviceService from './service.service'
export * as postService from './post.service'
export * as authService from './auth.service'
export * as patientService from './patient.service'